const authPageCopy = {
  ar: {
    common: {
      required: "مطلوب",
      optional: "اختياري",
      showPassword: "إظهار كلمة المرور",
      hidePassword: "إخفاء كلمة المرور",
      orContinueWith: "أو تابع باستخدام",
      googleLoading: "جارٍ الاتصال بـ Google…",
      googleError: "تعذر إكمال الدخول عبر Google. حاول مرة أخرى.",
      emailRequired: "أدخل بريدك الإلكتروني.",
      emailInvalid: "أدخل عنوان بريد إلكتروني صحيحًا.",
      passwordRequired: "أدخل كلمة المرور.",
      genericError: "تعذر إكمال الطلب الآن. تحقق من البيانات وحاول مرة أخرى."
    },
    signIn: {
      eyebrow: "دخول إلى مساحة العمل",
      heroTitle: "حوّل يوم الفريق إلى مسار عمل واحد وواضح.",
      heroText: "المشاريع والاجتماعات والملفات ومساعدك الذكي تعمل معًا في سياق لا يتشتت بين الأدوات.",
      title: "مرحبًا بعودتك",
      subtitle: "أدخل بياناتك للعودة إلى مساحة عملك.",
      email: "البريد الإلكتروني للعمل",
      emailPlaceholder: "name@company.com",
      password: "كلمة المرور",
      passwordPlaceholder: "أدخل كلمة المرور",
      remember: "تذكّرني",
      forgotPassword: "نسيت كلمة المرور؟",
      submit: "تسجيل الدخول",
      submitting: "جارٍ تسجيل الدخول…",
      google: "الدخول عبر Google",
      noAccount: "ليس لديك حساب؟",
      createAccount: "أنشئ حسابًا",
      signInError: "لم نتمكن من تسجيل الدخول. تحقق من البريد وكلمة المرور ثم حاول مجددًا."
    },
    signUp: {
      eyebrow: "ابدأ مساحة شركتك",
      heroTitle: "ابنِ ذاكرة عمل مشتركة منذ اليوم الأول.",
      heroText: "اجمع الفريق والمشاريع والاجتماعات في مساحة ذكية تتعلم من سياق شركتك وتحافظ عليه.",
      title: "أنشئ حساب شركتك",
      subtitle: "خطوة واحدة تفصلك عن مساحة Teamoria الخاصة بفريقك.",
      fullName: "الاسم الكامل",
      fullNamePlaceholder: "اكتب اسمك الكامل",
      fullNameRequired: "أدخل اسمك الكامل.",
      email: "البريد الإلكتروني للعمل",
      emailPlaceholder: "name@company.com",
      companyName: "اسم الشركة",
      companyPlaceholder: "مثال: شركة أفق",
      companyRequired: "أدخل اسم الشركة.",
      ownerTitle: "حساب مالك الشركة",
      ownerText: "ستُنشأ مساحة العمل بصلاحيات المالك، ويمكنك دعوة الفريق لاحقًا.",
      password: "كلمة المرور",
      passwordPlaceholder: "8 أحرف على الأقل",
      passwordShort: "يجب ألا تقل كلمة المرور عن 8 أحرف.",
      submit: "إنشاء مساحة العمل",
      submitting: "جارٍ إنشاء المساحة…",
      google: "التسجيل عبر Google",
      haveAccount: "لديك حساب بالفعل؟",
      login: "سجّل الدخول",
      signUpError: "تعذر إنشاء الحساب. راجع البيانات وحاول مرة أخرى."
    },
    reset: {
      eyebrow: "استعادة الوصول",
      heroTitle: "استعد الوصول من دون أن تفقد سياق عملك.",
      heroText: "سنرسل رابطًا آمنًا إلى بريدك لتعود إلى مشاريعك واجتماعاتك وذاكرة فريقك.",
      title: "إعادة تعيين كلمة المرور",
      subtitle: "أدخل بريد العمل وسنرسل إليك رابط استعادة آمنًا.",
      email: "البريد الإلكتروني للعمل",
      emailPlaceholder: "name@company.com",
      submit: "إرسال رابط الاستعادة",
      submitting: "جارٍ الإرسال…",
      successTitle: "تحقق من بريدك",
      successMessage: "إذا كان البريد مرتبطًا بحساب، فقد أرسلنا إليه رابط إعادة تعيين كلمة المرور.",
      remember: "تذكّرت كلمة المرور؟",
      backToLogin: "العودة إلى تسجيل الدخول",
      error: "تعذر إرسال رابط الاستعادة الآن. حاول مرة أخرى."
    },
    otp: {
      eyebrow: "تأكيد الهوية",
      heroTitle: "خطوة قصيرة تحمي مساحة شركتك.",
      heroText: "أكد بريدك الإلكتروني لنضمن أن هوية كل عضو وبيانات كل مساحة تبقى في المكان الصحيح.",
      title: "تحقق من بريدك",
      subtitle: "أدخل رمز التحقق المكوّن من 6 أرقام الذي أرسلناه إليك.",
      code: "رمز التحقق",
      digitLabel: "الرقم {number} من رمز التحقق",
      submit: "تأكيد البريد الإلكتروني",
      submitting: "جارٍ التحقق…",
      resend: "إرسال رمز جديد",
      resending: "جارٍ الإرسال…",
      backToSignup: "العودة إلى إنشاء الحساب",
      noPending: "لم نعثر على بريد ينتظر التحقق. أنشئ حسابًا أولًا.",
      createFirst: "أنشئ حسابًا أولًا حتى نتمكن من التحقق من البريد.",
      codeRequired: "أدخل رمز التحقق.",
      codeInvalid: "أدخل رمز التحقق المكوّن من 6 أرقام.",
      sent: "أرسلنا رمز تحقق إلى بريدك الإلكتروني.",
      resent: "أرسلنا رمز تحقق جديدًا.",
      verified: "تم تأكيد البريد. جارٍ نقلك إلى مساحة العمل…",
      resendNeedsEmail: "أعد إنشاء الحساب حتى نعرف البريد الذي سنرسل إليه الرمز.",
      sendError: "تعذر إرسال رمز التحقق. حاول مرة أخرى.",
      verifyError: "تعذر تأكيد الرمز. راجعه ثم حاول مرة أخرى."
    },
    onboarding: {
      eyebrow: "إعداد الشركة",
      heroTitle: "هيّئ مساحة شركتك لتعمل بطريقتكم.",
      heroText: "هذه البيانات تبني نقطة الالتقاء التي ترتبط بها المشاريع والموظفون والملفات والصلاحيات والذكاء الاصطناعي.",
      title: "ملف الشركة",
      subtitle: "أكمل المعلومات الأساسية لإنشاء مساحة العمل المرتبطة بحساب المالك.",
      companyName: "اسم الشركة",
      companyPlaceholder: "مثال: شركة أفق",
      industry: "مجال العمل",
      industryPlaceholder: "مثال: البرمجيات",
      website: "الموقع الإلكتروني",
      websitePlaceholder: "https://company.com",
      address: "العنوان",
      addressPlaceholder: "المدينة، الدولة",
      submit: "إنشاء الشركة والمتابعة",
      submitting: "جارٍ إنشاء الشركة…",
      nameRequired: "أدخل اسم الشركة للمتابعة.",
      error: "تعذر إنشاء الشركة الآن. راجع البيانات وحاول مرة أخرى."
    }
  },
  en: {
    common: {
      required: "Required",
      optional: "Optional",
      showPassword: "Show password",
      hidePassword: "Hide password",
      orContinueWith: "or continue with",
      googleLoading: "Connecting to Google…",
      googleError: "Google sign-in could not be completed. Please try again.",
      emailRequired: "Enter your email address.",
      emailInvalid: "Enter a valid email address.",
      passwordRequired: "Enter your password.",
      genericError: "We could not complete the request. Check your details and try again."
    },
    signIn: {
      eyebrow: "Workspace access",
      heroTitle: "Turn your team’s day into one clear flow of work.",
      heroText: "Projects, meetings, files, and your AI assistant stay connected in context instead of scattered across tools.",
      title: "Welcome back",
      subtitle: "Enter your details to return to your workspace.",
      email: "Work email",
      emailPlaceholder: "name@company.com",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      remember: "Remember me",
      forgotPassword: "Forgot password?",
      submit: "Sign in",
      submitting: "Signing in…",
      google: "Sign in with Google",
      noAccount: "New to Teamoria?",
      createAccount: "Create an account",
      signInError: "We could not sign you in. Check your email and password, then try again."
    },
    signUp: {
      eyebrow: "Start your company workspace",
      heroTitle: "Build a shared memory for work from day one.",
      heroText: "Bring your team, projects, and meetings into an intelligent workspace that learns and preserves company context.",
      title: "Create your company account",
      subtitle: "You’re one step away from your team’s Teamoria workspace.",
      fullName: "Full name",
      fullNamePlaceholder: "Enter your full name",
      fullNameRequired: "Enter your full name.",
      email: "Work email",
      emailPlaceholder: "name@company.com",
      companyName: "Company name",
      companyPlaceholder: "e.g. Horizon Labs",
      companyRequired: "Enter your company name.",
      ownerTitle: "Company owner account",
      ownerText: "Your workspace starts with owner access. You can invite your team next.",
      password: "Password",
      passwordPlaceholder: "At least 8 characters",
      passwordShort: "Use at least 8 characters.",
      submit: "Create workspace",
      submitting: "Creating workspace…",
      google: "Sign up with Google",
      haveAccount: "Already have an account?",
      login: "Sign in",
      signUpError: "We could not create your account. Check the details and try again."
    },
    reset: {
      eyebrow: "Recover access",
      heroTitle: "Restore access without losing your work context.",
      heroText: "We’ll send a secure link to your email so you can return to your projects, meetings, and team memory.",
      title: "Reset your password",
      subtitle: "Enter your work email and we’ll send you a secure recovery link.",
      email: "Work email",
      emailPlaceholder: "name@company.com",
      submit: "Send recovery link",
      submitting: "Sending…",
      successTitle: "Check your email",
      successMessage: "If an account exists for this email, we sent a password reset link.",
      remember: "Remembered your password?",
      backToLogin: "Back to sign in",
      error: "We could not send the recovery link. Please try again."
    },
    otp: {
      eyebrow: "Identity check",
      heroTitle: "One short step keeps your company workspace protected.",
      heroText: "Confirm your email so every member’s identity and every workspace’s data stay in the right place.",
      title: "Verify your email",
      subtitle: "Enter the 6-digit verification code we sent to your email.",
      code: "Verification code",
      digitLabel: "Verification code digit {number}",
      submit: "Verify email",
      submitting: "Verifying…",
      resend: "Send a new code",
      resending: "Sending…",
      backToSignup: "Back to sign up",
      noPending: "No pending email was found. Create an account first.",
      createFirst: "Create an account before verifying your email.",
      codeRequired: "Enter the verification code.",
      codeInvalid: "Enter the 6-digit verification code.",
      sent: "A verification code was sent to your email.",
      resent: "A new verification code was sent.",
      verified: "Email verified. Taking you to your workspace…",
      resendNeedsEmail: "Start sign-up again so we know where to send the code.",
      sendError: "We could not send the verification code. Please try again.",
      verifyError: "We could not verify that code. Check it and try again."
    },
    onboarding: {
      eyebrow: "Company setup",
      heroTitle: "Shape your workspace around the way your company works.",
      heroText: "This profile becomes the shared point for projects, people, files, permissions, billing, and AI context.",
      title: "Company profile",
      subtitle: "Complete the essentials to create the workspace linked to your owner account.",
      companyName: "Company name",
      companyPlaceholder: "e.g. Horizon Labs",
      industry: "Industry",
      industryPlaceholder: "e.g. Software",
      website: "Website",
      websitePlaceholder: "https://company.com",
      address: "Address",
      addressPlaceholder: "City, country",
      submit: "Create company and continue",
      submitting: "Creating company…",
      nameRequired: "Enter your company name to continue.",
      error: "We could not create the company. Check the details and try again."
    }
  }
};

export function getAuthPageCopy(language, page) {
  const locale = authPageCopy[language] || authPageCopy.en;
  return { ...locale.common, ...locale[page] };
}

export function getLocalizedRequestError(error, language, fallback) {
  const message = String(error?.message || "").trim();
  if (!message) return fallback;
  if (language === "en" || /[\u0600-\u06ff]/.test(message)) return message;
  return fallback;
}
