services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_ORIGIN: ${VITE_API_ORIGIN}
        VITE_API_VERSION: ${VITE_API_VERSION}
        VITE_API_KEY: ${VITE_API_KEY}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_REVERB_APP_KEY: ${VITE_REVERB_APP_KEY}
        VITE_REVERB_HOST: ${VITE_REVERB_HOST}
        VITE_REVERB_PORT: ${VITE_REVERB_PORT}
        VITE_REVERB_SCHEME: ${VITE_REVERB_SCHEME}
        VITE_REVERB_AUTH_ENDPOINT: ${VITE_REVERB_AUTH_ENDPOINT}
    ports:
      - "${APP_PORT:-3000}:80"
    env_file:
      - .env
    networks:
      - frontend
    restart: always

networks:
  frontend:
    driver: bridge
