services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_ORIGIN: ${VITE_API_ORIGIN}
        VITE_API_VERSION: ${VITE_API_VERSION}
        VITE_API_KEY: ${VITE_API_KEY}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "${APP_PORT:-3000}:80"
    env_file:
      - .env
    networks:
      - frontend
    restart: always

networks:
  frontend:
    driver: bridge