FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_API_ORIGIN
ARG VITE_API_BASE_URL
ARG VITE_API_VERSION
ARG VITE_API_KEY
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_REVERB_APP_KEY
ARG VITE_REVERB_HOST
ARG VITE_REVERB_PORT
ARG VITE_REVERB_SCHEME
ARG VITE_REVERB_AUTH_ENDPOINT

ENV VITE_API_ORIGIN=$VITE_API_ORIGIN
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_VERSION=$VITE_API_VERSION
ENV VITE_API_KEY=$VITE_API_KEY
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_REVERB_APP_KEY=$VITE_REVERB_APP_KEY
ENV VITE_REVERB_HOST=$VITE_REVERB_HOST
ENV VITE_REVERB_PORT=$VITE_REVERB_PORT
ENV VITE_REVERB_SCHEME=$VITE_REVERB_SCHEME
ENV VITE_REVERB_AUTH_ENDPOINT=$VITE_REVERB_AUTH_ENDPOINT

COPY package.json package-lock.json* ./
RUN npm ci --production=false

COPY . .

RUN npm run build
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
